apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.restFederatorServer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.restFederatorServer.service.type }}
  selector:
    app: {{ .Values.restFederatorServer.name }}
  ports:
    - name: http
      port: {{ .Values.restFederatorServer.service.port }}
